---
- name: Test nginx config
  ansible.builtin.command: nginx -t
  register: nginx_test
  changed_when: false

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted