---
- name: Ensure virtualenv exists
  ansible.builtin.command: python3 -m venv {{ app_dir }}/venv
  args:
    creates: "{{ app_dir }}/venv/bin/activate"
  become: yes
  become_user: "{{ app_user }}"

- name: Upload Flask app file
  ansible.builtin.copy:
    src: app.py
    dest: "{{ app_dir }}/app.py"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Upload requirements.txt
  ansible.builtin.copy:
    src: requirements.txt
    dest: "{{ app_dir }}/requirements.txt"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Install Python dependencies in venv
  ansible.builtin.pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"
    virtualenv_python: python3

- name: Render environment file
  ansible.builtin.template:
    src: ".env.j2"
    dest: "/etc/{{ app_name }}.env"
    owner: "root"
    group: "root"
    mode: "0640"

- name: Install systemd service for Gunicorn
  ansible.builtin.template:
    src: "flaskapp.service.j2"
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload

- name: Enable and start {{ app_name }}
  ansible.builtin.service:
    name: "{{ app_name }}"
    state: started
    enabled: yes
