---
- name: Ensure virtualenv exists
  ansible.builtin.command: python3 -m venv {{ app_dir }}/venv
  args:
    creates: "{{ app_dir }}/venv/bin/activate"
  become: yes
  become_user: "{{ app_user }}"

- name: Upload Flask app file
  ansible.builtin.copy:
    src: app.py
    dest: "{{ app_dir }}/app.py"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Create templates directory
  ansible.builtin.file:
    path: "{{ app_dir }}/templates"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"

- name: Create static directories
  ansible.builtin.file:
    path: "{{ app_dir }}/static/{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"
  loop:
    - css
    - images

- name: Upload HTML templates
  ansible.builtin.copy:
    src: "templates/{{ item }}"
    dest: "{{ app_dir }}/templates/{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"
  loop:
    - index.html
    - health.html
    - db.html

- name: Upload CSS file
  ansible.builtin.copy:
    src: static/css/style.css
    dest: "{{ app_dir }}/static/css/style.css"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Upload requirements.txt
  ansible.builtin.copy:
    src: requirements.txt
    dest: "{{ app_dir }}/requirements.txt"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Install Python dependencies in venv
  ansible.builtin.pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"
    virtualenv_python: python3

- name: Render environment file
  ansible.builtin.template:
    src: ".env.j2"
    dest: "/etc/{{ app_name }}.env"
    owner: "root"
    group: "root"
    mode: "0640"

- name: Install systemd service for Gunicorn
  ansible.builtin.template:
    src: "flaskapp.service.j2"
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload

- name: Enable and start {{ app_name }}
  ansible.builtin.service:
    name: "{{ app_name }}"
    state: restarted
    enabled: yes
